services:
  # 1. DATABASE POSTGRESQL (LOKAL DOCKER)
  db:
    image: postgres:15-alpine
    container_name: financesmart-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: financesmart_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  # 2. BACKEND (Tambahkan ini supaya backend-mu juga jalan di Docker)
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    container_name: financesmart-backend
    ports:
      - "5000:5000"
    environment:
      # Perhatikan host-nya pakai 'db' bukan localhost
      DATABASE_URL: "postgresql://postgres:password123@db:5432/financesmart_db?schema=public"
    depends_on:
      - db

  # 3. PRISMA STUDIO
  studio:
    image: node:20-alpine
    container_name: financesmart-studio
    working_dir: /app
    volumes:
      - ./backend:/app
    # Kita perlu install prisma dulu di dalam container studio agar perintahnya jalan
    command: sh -c "npm install && npx prisma studio --browser none --port 5555"
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://postgres:password123@db:5432/financesmart_db?schema=public"
    depends_on:
      - db

  # 4. FRONTEND
  frontend:
    build: ./frontend
    container_name: financesmart-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
volumes:
  db-data:
